### ISSUE TITLE
Helper_functions documentation spell check

### ISSUE THREAD

**Issue by drcandacemakedamoore** [resurfemg-org/ReSurfEMG#101]
helper_functions documentation in triple qoutes (what ends up in the module documentation) needs to be spell- checked.

**Comment by ElineOppersma** [comment]
Done with commit 9c28a80

**Comment by drcandacemakedamoore** [comment]
I see some spelling errors after the re-writing. IN addition, these changes now need to be applied across branches open on PRs.
