### ISSUE TITLE
Finish guide to notebooks

### ISSUE THREAD

**Issue by drcandacemakedamoore** [resurfemg-org/ReSurfEMG#103]
Write a hyperlinked guide to notebooks markdown file to be linked from the readme. This way outside researchers can use  the notebooks without having to wade through all of them

**Comment by drcandacemakedamoore** [comment]
Already started with examples, so the only task left is to put in all the notebooks, in the same format as shown.

**Comment by rspwarnaar** [comment]
Fixed by Eline with #235
