### ISSUE TITLE
Review Rob's binder for pub binder

### ISSUE THREAD

**Issue by ElineOppersma** [resurfemg-org/ReSurfEMG#111]
Duplicate with review of #110

**Comment by drcandacemakedamoore** [comment]
This code needs to be reviewed by everyone else.

**Comment by drcandacemakedamoore** [comment]
The core binder breaks because it doesn't point at the right data i.e. you have the line 
main_output_dir = '../not_pushed/Output_data/'

Also you have some junk you probably meant to pull in there.
