### ISSUE TITLE
Identify causes of differences in amplitudes EMG processing pipelines

### ISSUE THREAD

**Issue by rspwarnaar** [resurfemg-org/ReSurfEMG#119]
The RMS amplitude of the diaphragm using the default pipeline in the dashboard looks like this for a specific dataset. Note the amplitude to be in a range of 0.002 uV. I found similar results for other data sets, so this is not patient or recording specific.
 
![afbeelding](https://user-images.githubusercontent.com/89922216/194007706-a4b70cd9-c09e-4937-bf52-5276e0b68e3e.png)

When I compare this section of data analysed with my notebook for my paper (neuromuscular_efficiency_3lead_for_pub.ipynb) the amplitude is in the ~20 uV range, which is about a 10.000 fold higher. 

 
![afbeelding](https://user-images.githubusercontent.com/89922216/194007764-ec2d71eb-9af4-49d2-b3bc-9004983c9b2d.png)

The latter (amplitudes in the order of several to tenths of uV) is way more comparable to values found in literature. So I was wondering what is happening in the current default pipeline that reduces the amplitudes by this much.

**Comment by ElineOppersma** [comment]
Problem identified: scaling of ICA will be adapted with ICA factor.
