### ISSUE TITLE
See file name in every tab of dashboard

### ISSUE THREAD

**Issue by drcandacemakedamoore** [resurfemg-org/ReSurfEMG#121]
Please always @wbaccinelli show file names in each tab of dashboard

**Comment by wbaccinelli** [comment]
At the moment, there are no components in Dash to get the local path of a file. What we would need is a file/folders browser, to let the user pick the file location (getting also rid of the Upload component).  A [feature request](https://github.com/plotly/dash-core-components/issues/639) is pending in Dash, maybe it will be available some day.

A possible workaround is to make use of a string-based explorer like [this](https://github.com/eliasdabbas/dash-file-browser). it is quite ugly, but potentially working.

Another solution is to bypass Dash and using some native  python GUI components like tkinter  as shown [here](https://stackoverflow.com/questions/71163507/python-dash-tkinter-openfile-dialog-works-fine-only-the-first-time-but-fails-a). I tried this approach and, even if it might work, the issues with the threading and the hybrid GUI are huge and unpredictable.

**Comment by wbaccinelli** [comment]
The final decision is to use a custom implementation of the file explorer, adding the possibility to copy and paste the path to the file
