### ISSUE TITLE
Make notebook based on existing ML model to run multiple datasets

### ISSUE THREAD

**Issue by ElineOppersma** [resurfemg-org/ReSurfEMG#150]
We want to make a notebook to compare on and offset definition of every single breath, using different methods:
ML svm
ML lr
entropy (90-50% threshold)
single cut entropy 70%

**Comment by drcandacemakedamoore** [comment]
Will be handled partly by an API instead, notebook too cumbersome for user. Only analysus i.e.entropy (90-50% threshold)
single cut entropy 70% will be done in a notebook. ML svm and ML lr will be options in the command line, which now contains pre-processing default. Please examine cli module, and test with readme instructions.

**Comment by drcandacemakedamoore** [comment]
PR #171
