### ISSUE TITLE
Fix bug in Config module

### ISSUE THREAD

**Issue by ReSurfEMG** [resurfemg-org/ReSurfEMG#173]
template commented out at bottom of test.py, imports i.e. json etc. already in file

**Comment by drcandacemakedamoore** [comment]
Actually when you uncomment, you will see we have a bug in config, it needs fixing

**Comment by drcandacemakedamoore** [comment]
fixed on main [e37a5eb](https://github.com/ReSurfEMG/ReSurfEMG/commit/e37a5eb76d68f94069b5210e6d1d77adf79bb7d8)
