### ISSUE TITLE
Descriptor: rise slope

### ISSUE THREAD

**Issue by ReSurfEMG** [resurfemg-org/ReSurfEMG#202]
write function for rise slope , given onset and offset, and adding a smoothing algorithm, the slope going up to max from baseline per breath

**Comment by drcandacemakedamoore** [comment]
@wbaccinelli looks like I forgot to have someone review this, and it should be reviewed before closing . it's the function  pseudo_slope()

**Comment by wbaccinelli** [comment]
It is not clear to me which is the definition of slope we want to use. The one implemented in the function is the mean slope from the onset to the maximum. If we want to have the slope of a specific part of the signal (e.g., the onset of the breath), we should compute the derivative of the shape in that specific point, In our case it would be the amplitude difference of two consecutive samples divided by the sampling period. To reject some noise, it could then be an idea to take the mean of the the derivative over some points.

**Comment by wbaccinelli** [comment]
We should also be careful in applying the smoothing behind the scenes. If the preprocessing stage included the extraction of the envelope, and that is the input to the function, an additional smoothing process might negatively affect the signal

**Comment by drcandacemakedamoore** [comment]
OK, I'm adding a parameter that gives the option to turn on or off smoothing....wient into pull request #217  If we want slopes at different points or a different calculation it  should be in separate issues from this opened by scientists using the code.
