### ISSUE TITLE
Polybench converter function

### ISSUE THREAD

**Issue by drcandacemakedamoore** [resurfemg-org/ReSurfEMG#35]
Write a function to convert (Duiverman type) polybench files down to array that can be fed to interfaces

**Comment by drcandacemakedamoore** [comment]
The Duiverman polybench files can be read with Poly5Reader. There is now also a function to read in their processed csv files ( dvrmn_csv_to_array) and get the postprocessed frequency ( dvrmn_csv_freq_find)

**Comment by drcandacemakedamoore** [comment]
We got info on the 18 lead type Poly5 file, a function for it can now be written

**Comment by ElineOppersma** [comment]
poly_dvrman pull request for line 109 (#118)
