### ISSUE TITLE
first release

### ISSUE THREAD

**Issue by drcandacemakedamoore** [resurfemg-org/ReSurfEMG#43]
Try to do a release of version 0.0.1 before July 6th

**Comment by drcandacemakedamoore** [comment]
We have a Linux and Windows release. These need checking already.

**Comment by ReSurfEMG** [comment]
We now changed the code so the next release can be truly cross platform. Windows, Linux, Mac. **The releases need to be checked and the code that calls the libraries adjusted.**  After this we will do a version 0.0.1, and inform collaborators
