### ISSUE TITLE
interface for EMG alone

### ISSUE THREAD

**Issue by ReSurfEMG** [resurfemg-org/ReSurfEMG#55]
Currently in IE and Chrome, if you try to openan EMG by itself, you open the previous Draeger data. We need to force it to have nothing there instead

**Comment by wbaccinelli** [comment]
Add clear data functionality

**Comment by drcandacemakedamoore** [comment]
Completed, and works in Edge, CHrome and Firefox as expected! We need to find someone with a Mac and Safari eventually to double check it behaves there well as well.
