### ISSUE TITLE
Create installer and executable for dashboard

### ISSUE THREAD

**Issue by wbaccinelli** [resurfemg-org/ReSurfEMG#63]
We would like to have the dashboard to be launched through an executable file. For this purpose we need to have an executable, created through an installer. The executable shall launch the dashboard, avoiding the use of the terminal.

**Comment by drcandacemakedamoore** [comment]
On my machine it builds an .exe file, but this file when clicked launches only a terminal that then shuts. Maybe the browsers need to be configured in a certain way? Needs exploration

**Comment by drcandacemakedamoore** [comment]
OK, once right environment is there it works on Windows. I'll put a seperate issue for myself to do testing on Apple and Linux with multiple browsers
