### ISSUE TITLE
Add test in testing for picking emg by heart component

### ISSUE THREAD

**Issue by drcandacemakedamoore** [resurfemg-org/ReSurfEMG#65]

**Comment by drcandacemakedamoore** [comment]
OOps, mistake

**Comment by drcandacemakedamoore** [comment]
Added one test, needs another test

**Comment by drcandacemakedamoore** [comment]
pick_lowest_correlation_array that function needs a test- it should be in there

**Comment by drcandacemakedamoore** [comment]
Reassigned to Rob

**Comment by rspwarnaar** [comment]
The test_pick_more_peaks_array doesn't check for the correct array being identified, but it only checks for the output arrays to be the same length.

The test_pick_lowest_correlation_array does this by assuring the sum of the selected array matches the sum of the wanted array. Maybe introducing similar code in test_pick_more_peaks_array:
`sample_emg_filtered[2,20] = 0
        sample_emg_filtered[2,40] = 0
        sample_emg_filtered[2,80] = 0
        sample_emg_filtered[2,21] = 100
        sample_emg_filtered[2,42] = 100
        sample_emg_filtered[2,81] = 100
        components = sample_emg_filtered[1], sample_emg_filtered[2]
        emg = pick_more_peaks_array(components)
        self.assertEqual(
            sum(emg),
            sum(sample_emg_filtered[2]) ,
        )`

**Comment by drcandacemakedamoore** [comment]
You are right, but technically the only code in this issue here to look at was  to look at test_pick_lowest_correlation_array . Good that you noticed the fact that  test_pick_more_peaks_array doesn't really prove it works... this is sanity testing, not correctness testing. We can add other issues to improve tests like test_pick_more_peaks_array later.
