### ISSUE TITLE
Implement method for QRS complex identification 

### ISSUE THREAD

**Issue by wbaccinelli** [resurfemg-org/ReSurfEMG#70]
In the [gating function](https://github.com/ReSurfEMG/ReSurfEMG/blob/5ba2b2051d972f449f61fdbc3d3ce2b6253b50b8/resurfemg/helper_functions.py#L860) the position of the QRS complex in the signal has to be known, in order to apply the method. At the moment we have no method in the resurfemg library to identify it, and we make use of scipy.signal.find_peaks. This is not a reliable way for the complex identification, and a devoted method should be implemented.

**Comment by drcandacemakedamoore** [comment]
Not sure if still relevant, let's look at https://hooman650.github.io/ECG-QRS.html

**Comment by drcandacemakedamoore** [comment]
find_peaks_in_ecg_signal function is written but now needs testing on real data. please feed it ECGs

**Comment by ElineOppersma** [comment]
Data output format is not as specified (~numpy.ndarray) but is a tuple. Please change documentation. @drcandacemakedamoore

**Comment by drcandacemakedamoore** [comment]
Excellent catch @ElineOppersma , the documentation is updated
