### ISSUE TITLE
Generalize compute_ICA_two_comp

### ISSUE THREAD

**Issue by wbaccinelli** [resurfemg-org/ReSurfEMG#71]
In the current version, [compute_ICA_two_comp](https://github.com/ReSurfEMG/ReSurfEMG/blob/5ba2b2051d972f449f61fdbc3d3ce2b6253b50b8/resurfemg/helper_functions.py#L435) takes as input the matrix of the signals, containing all the leads, and assumes that lead 0 is the heart lead and that lead 2 is the EMG signal to be split. 
We would like to have a more general approach, where the leads can be specified.

**Comment by drcandacemakedamoore** [comment]
Oops, I forgot Walter already opened this issue essentially, and now it's duplicated...I'll close both when I finish it.

**Comment by ReSurfEMG** [comment]
I closed this with multi_lead_type.compute_ICA_n_comp_selective_zeroing, and it had a new duplicated issue.
