### ISSUE TITLE
Video showing the present exectuable interface in action

### ISSUE THREAD

**Issue by drcandacemakedamoore** [resurfemg-org/ReSurfEMG#77]
Should be sent to participants before the workshop as part of prep package

**Comment by drcandacemakedamoore** [comment]
There is now one up on the learning rep (same as one sent out), please review for any major problems, someone else

**Comment by wbaccinelli** [comment]
I think this is very good for now!

**Comment by drcandacemakedamoore** [comment]
OK then, we will close the issue now that it has been reviewed by not the maker (me)
